# Generated by Django 4.1 on 2022-10-02 22:56

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket', models.CharField(max_length=200)),
                ('giat', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
                ('tgl', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Giat',
            },
        ),
        migrations.CreateModel(
            name='Pbfree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jk', models.CharField(max_length=10)),
                ('td', models.CharField(max_length=200, null=True)),
                ('usia', models.IntegerField(null=True)),
                ('dx', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat', models.CharField(max_length=200)),
                ('nohp', models.CharField(max_length=200, null=True)),
                ('tgl', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Pengobatan',
            },
        ),
        migrations.CreateModel(
            name='Telp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('notelp', models.CharField(max_length=200, null=True)),
                ('lokasi', models.CharField(max_length=200, null=True)),
                ('kategori', models.CharField(max_length=200, null=True)),
                ('subkategori', models.CharField(max_length=200, null=True)),
                ('detailkategori', models.CharField(max_length=200, null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('startcall', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Telp',
            },
        ),
        migrations.CreateModel(
            name='Video_giat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('giat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spgdt.giat')),
            ],
            options={
                'verbose_name_plural': 'Video_giat',
                'ordering': ['-added'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='filevideo/%y')),
                ('giat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spgdt.giat')),
            ],
            options={
                'verbose_name_plural': 'Video',
            },
        ),
    ]
